# Generated by Django 6.0 on 2025-12-22 17:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participant_profile', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('affiliation', models.CharField(max_length=255)),
                ('affiliation_department', models.CharField(max_length=255)),
                ('position', models.CharField(max_length=100)),
            ],
        ),
    ]
