# Generated by Django 6.0 on 2026-01-28 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='position',
        ),
    ]
