# Generated by Django 6.0 on 2026-08-13 20:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_update', models.DateTimeField(auto_now=True, db_column='last_update')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('is_active', models.BooleanField(db_column='is_active')),
                ('title', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('resource_id', models.PositiveIntegerField()),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
            ],
            options={
                'db_table': 'scheduled_event',
                'indexes': [models.Index(fields=['resource_type', 'resource_id'], name='scheduled_e_resourc_ccff5f_idx')],
            },
        ),
    ]
