# Generated by Django 6.0 on 2026-08-14 02:12

import apps.program.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("program", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Keynote",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_update", models.DateTimeField(auto_now=True, db_column="last_update")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_column="created_at")),
                ("is_active", models.BooleanField(db_column="is_active")),
                ("speaker", models.TextField()),
            ],
            options={
                "db_table": "keynote",
            },
        ),
        migrations.CreateModel(
            name="Trip",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("last_update", models.DateTimeField(auto_now=True, db_column="last_update")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_column="created_at")),
                ("is_active", models.BooleanField(db_column="is_active")),
                ("destination", models.TextField()),
                ("image", models.ImageField(blank=True, null=True, upload_to="scheduled_events/trip/")),
            ],
            options={
                "db_table": "trip",
            },
        ),
    ]
