# Generated by Django 6.0 on 2026-08-28 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0002_keynote_trip'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=64, unique=True)),
            ],
            options={
                'db_table': 'tag',
                'ordering': ['-description'],
            },
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='lounge',
            field=models.CharField(default='Sala Uxmal', max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='end_time',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='start_time',
            field=models.DateTimeField(),
        ),
        migrations.AddField(
            model_name='scheduledevent',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='scheduled_events', to='program.tag'),
        ),
    ]
