# Generated by Django 6.0 on 2026-08-29 02:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('program', '0003_tag_scheduledevent_lounge_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledevent',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='scheduled_events/images/'),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='description',
            field=models.TextField(max_length=100),
        ),
        migrations.AlterField(
            model_name='scheduledevent',
            name='title',
            field=models.TextField(max_length=100),
        ),
    ]
