# Generated by Django 6.0 on 2025-12-22 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Abstract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('co_authors', models.TextField(help_text='Lista de coautores')),
                ('presentation_type', models.CharField(choices=[('oral', 'Oral'), ('oral_default_poster', 'Oral (Default Poster)'), ('poster', 'Poster'), ('young_oral', 'Young Oral'), ('young_oral_default_poster', 'Young Oral (Default Poster)')], default='poster', max_length=50)),
                ('abstract_file', models.FileField(upload_to='abstracts/files/')),
                ('status', models.CharField(choices=[('submitted', 'Submitted'), ('under_review', 'Under Review'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='submitted', max_length=20)),
                ('submission_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
