# Generated by Django 6.0 on 2026-07-24 03:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_participant_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dinner',
            name='participant',
        ),
        migrations.RemoveField(
            model_name='participant',
            name='user',
        ),
        migrations.DeleteModel(
            name='Tour',
        ),
        migrations.DeleteModel(
            name='Dinner',
        ),
        migrations.DeleteModel(
            name='Participant',
        ),
    ]
