# Generated by Django 6.0 on 2026-07-24 03:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0003_remove_dinner_participant_remove_participant_user_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='participant', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('affiliation', models.CharField(blank=True, max_length=100)),
                ('job_title', models.CharField(blank=True, max_length=100)),
                ('field_of_study', models.CharField(blank=True, max_length=100)),
                ('needs_visa', models.BooleanField(default=False)),
                ('invitation_letter', models.FileField(blank=True, default=None, upload_to='users/invitation_letter/')),
                ('student_proof', models.FileField(blank=True, default=None, null=True, upload_to='users/student_proof/')),
            ],
            options={
                'db_table': 'participant',
            },
        ),
        migrations.CreateModel(
            name='Tour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=48)),
                ('description', models.TextField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='tours/image/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('participant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='participants.participant')),
                ('will_assist_dinner', models.BooleanField(default=False)),
                ('has_dietary_restriction', models.BooleanField(default=False)),
                ('dietary_needs', models.CharField(blank=True, choices=[('', 'Not set'), ('veget', 'Vegetarian'), ('vegan', 'Vegan'), ('glut', 'Gluten-free'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('paleo', 'Paleo'), ('fish', 'Pescatarian'), ('other', 'Other restrictions')], default='', max_length=10)),
                ('other_dietary_needs', models.CharField(blank=True, max_length=75)),
                ('has_food_allergy', models.BooleanField(default=False)),
                ('food_allergies', models.CharField(blank=True, choices=[('', 'Not set'), ('milk', 'Milk'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('crustacean', 'Crustacean'), ('mollusk', 'Mollusk'), ('almond', 'Almond'), ('hazelnut', 'Hazelnut'), ('walnut', 'Walnut'), ('peanuts', 'Peanuts'), ('wheat', 'Wheat (Gluten)'), ('soybeans', 'Soybeans'), ('other', 'Other')], default='', max_length=10)),
                ('other_allergies', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
