# Generated by Django 6.0 on 2026-08-28 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('participants', '0002_rename_affiliation_participant_institution_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, default='', max_length=30),
        ),
    ]
