# Generated by Django 6.0 on 2026-04-21 04:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact_requests', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contactrequest',
            old_name='contact_date',
            new_name='created_at',
        ),
        migrations.RenameField(
            model_name='contactrequest',
            old_name='description',
            new_name='message',
        ),
    ]
