# Generated by Django 6.0 on 2026-06-26 04:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'ordering': ['institution']},
        ),
        migrations.RenameField(
            model_name='affiliation',
            old_name='nationality',
            new_name='country',
        ),
        migrations.RenameField(
            model_name='affiliation',
            old_name='institute',
            new_name='institution',
        ),
    ]
