# Generated by Django 6.0 on 2026-07-08 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0002_remove_affiliation_related_user_author_related_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='author',
            old_name='corresponding_author',
            new_name='is_corresponding_author',
        ),
    ]
