# Generated by Django 6.0 on 2026-07-13 22:14

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abstracts", "0003_rename_corresponding_author_author_is_corresponding_author"),
    ]

    operations = [
        # migrations.CreateModel(
        #     name="AbstractDeclaration",
        #     fields=[
        #         ("abstract", models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name="declarations", serialize=False, to="abstracts.abstract")),
        #         (
        #             "confirm_accuracy",
        #             models.BooleanField(
        #                 default=False, help_text="I confirm that I have reviewed this abstract and that all information is correct. I acknowledge that the content cannot be edited after final submission and will be published exactly as submitted.", verbose_name="Information Correctness"
        #             ),
        #         ),
        #         ("consent_publication", models.BooleanField(default=False, help_text="The submission of an abstract constitutes your consent to publication (e.g. congress website, programme, other promotions, etc.).", verbose_name="Consent to Publication")),
        #         ("submit_on_behalf", models.BooleanField(default=False, help_text="I confirm that I submit this abstract on behalf of all authors. The contact details saved are those of the first author, who is responsible for informing the others.", verbose_name="Submit on behalf of all authors")),
        #         ("commitment_attendance", models.BooleanField(default=False, help_text="The abstract submission constitutes a formal commitment by the first author to physically attend the ECP and present the abstract in the assigned session.", verbose_name="Commitment to Attend")),
        #         ("not_previously_published", models.BooleanField(default=False, help_text="I herewith confirm that the abstract has not been previously published.", verbose_name="Not Previously Published")),
        #         ("no_ai_used", models.BooleanField(default=False, help_text="I herewith confirm that the abstract was prepared without using the aid of AI tools (such as, but not limited to, ChatGPT).", verbose_name="No AI Tools Used")),
        #     ],
        #     options={
        #         "db_table": "abstract_declarations",
        #     },
        # ),
        migrations.AddField(
            model_name="affiliation",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="affiliation",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="author",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="author",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        # migrations.DeleteModel(
        #     name="AbstractDeclarations",
        # ),
        migrations.RenameModel(
            old_name="AbstractDeclarations",
            new_name="AbstractDeclaration",
        ),
    ]
