# Generated by Django 6.0 on 2026-07-13 22:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0004_abstractdeclaration_affiliation_created_at_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='affiliation',
            options={'ordering': ['-updated_at']},
        ),
        migrations.AlterField(
            model_name='abstractdeclaration',
            name='abstract',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='declarations', serialize=False, to='abstracts.abstract'),
        ),
        migrations.AlterModelTable(
            name='author',
            table='authors',
        ),
    ]
