# Generated by Django 6.0 on 2026-07-18 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ContactRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('subject', models.PositiveSmallIntegerField(choices=[(0, 'Posters'), (1, 'Talks'), (2, 'Visa Letters'), (3, 'Payments'), (4, 'Others')], default=4)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contact Request',
                'verbose_name_plural': 'Contact Requests',
                'db_table': 'contact_requests',
                'ordering': ['-created_at'],
            },
        ),
    ]
