# Generated by Django 6.0 on 2026-07-19 07:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abstracts', '0003_abstract_is_editable'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReviewAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'En revisión'), ('accepted', 'Aceptado'), ('declined', 'Rechazado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_column='status', default='submitted', max_length=16)),
                ('last_update', models.DateTimeField(auto_now=True, db_column='last_update')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to='abstracts.abstract')),
                ('assigned_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_reviews', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='review_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'review_assignment',
                'ordering': ['last_update'],
            },
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('submitted', 'En revisión'), ('accepted', 'Aceptado'), ('declined', 'Rechazado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_column='status', default='submitted', max_length=16)),
                ('comments', models.TextField()),
                ('suggestions', models.TextField()),
                ('submitted_at', models.DateTimeField(auto_now_add=True, db_column='created_at')),
                ('assignment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='reviews.reviewassignment')),
            ],
            options={
                'db_table': 'reviews',
            },
        ),
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(fields=('user', 'abstract'), name='unique_user_abstract_review_assignment'),
        ),
    ]
