# Generated by Django 6.0 on 2026-07-20 14:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['submitted_at']},
        ),
        migrations.AlterModelOptions(
            name='reviewassignment',
            options={'ordering': ['created_at']},
        ),
        migrations.AlterField(
            model_name='review',
            name='assignment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='reviews.reviewassignment'),
        ),
        migrations.AlterField(
            model_name='review',
            name='status',
            field=models.CharField(choices=[('pending', 'En revisión'), ('accepted', 'Aceptado'), ('declined', 'Rechazado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_column='status', default='pending', max_length=16),
        ),
        migrations.AlterField(
            model_name='reviewassignment',
            name='status',
            field=models.CharField(choices=[('pending', 'En revisión'), ('accepted', 'Aceptado'), ('declined', 'Rechazado'), ('completed', 'Completado'), ('cancelled', 'Cancelado')], db_column='status', default='pending', max_length=16),
        ),
    ]
