# Generated by Django 6.0 on 2026-07-25 06:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reviews', '0003_alter_review_assignment'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviewassignment',
            name='due_date',
            field=models.DateTimeField(db_column='due_date', default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviewassignment',
            name='is_active',
            field=models.BooleanField(db_column='is_active', default=True),
            preserve_default=False,
        ),
    ]
