# Generated by Django 6.0 on 2026-08-08 19:00

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0004_pdfgenerationjob'),
        ('reviews', '0004_reviewassignment_due_date_reviewassignment_is_active'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='reviewassignment',
            constraint=models.UniqueConstraint(condition=models.Q(('is_active', True)), fields=('abstract',), name='unique_active_review_assignment_per_abstract'),
        ),
    ]
