export function getCountryImage(country: string) {
    const target = countries.find((item: Country) => item.label === country || item.value === country)
    if (target)
        return <img
            loading="lazy"
            width="20"
            srcSet={`https://flagcdn.com/w40/${target.value.toString().toLowerCase()}.png 2x`}
            src={`https://flagcdn.com/w20/${target.value.toString().toLowerCase()}.png`}
            alt=""
        />;
    return null
}

export interface Country  {
    value: string,
    label: string,
    phone: string,
    suggested?: boolean
}

export const countries: Country[] = [
    { value: 'AF', label: 'Afghanistan', phone: '93' },
    { value: 'AL', label: 'Albania', phone: '355' },
    { value: 'DZ', label: 'Algeria', phone: '213' },
    { value: 'AX', label: 'Alland Islands', phone: '358' },
    { value: 'AS', label: 'American Samoa', phone: '1-684' },
    { value: 'AD', label: 'Andorra', phone: '376' },
    { value: 'AO', label: 'Angola', phone: '244' },
    { value: 'AI', label: 'Anguilla', phone: '1-264' },
    { value: 'AQ', label: 'Antarctica', phone: '672' },
    { value: 'AG', label: 'Antigua and Barbuda', phone: '1-268' },
    { value: 'AR', label: 'Argentina', phone: '54' },
    { value: 'AM', label: 'Armenia', phone: '374' },
    { value: 'AW', label: 'Aruba', phone: '297' },
    { value: 'AU', label: 'Australia', phone: '61', suggested: true },
    { value: 'AT', label: 'Austria', phone: '43' },
    { value: 'AZ', label: 'Azerbaijan', phone: '994' },
    { value: 'BS', label: 'Bahamas', phone: '1-242' },
    { value: 'BH', label: 'Bahrain', phone: '973' },
    { value: 'BD', label: 'Bangladesh', phone: '880' },
    { value: 'BB', label: 'Barbados', phone: '1-246' },
    { value: 'BY', label: 'Belarus', phone: '375' },
    { value: 'BE', label: 'Belgium', phone: '32' },
    { value: 'BZ', label: 'Belize', phone: '501' },
    { value: 'BJ', label: 'Benin', phone: '229' },
    { value: 'BM', label: 'Bermuda', phone: '1-441' },
    { value: 'BT', label: 'Bhutan', phone: '975' },
    { value: 'BO', label: 'Bolivia', phone: '591' },
    { value: 'BA', label: 'Bosnia and Herzegovina', phone: '387' },
    { value: 'BW', label: 'Botswana', phone: '267' },
    { value: 'BV', label: 'Bouvet Island', phone: '47' },
    { value: 'BR', label: 'Brazil', phone: '55' },
    { value: 'IO', label: 'British Indian Ocean Territory', phone: '246' },
    { value: 'VG', label: 'British Virgin Islands', phone: '1-284' },
    { value: 'BN', label: 'Brunei Darussalam', phone: '673' },
    { value: 'BG', label: 'Bulgaria', phone: '359' },
    { value: 'BF', label: 'Burkina Faso', phone: '226' },
    { value: 'BI', label: 'Burundi', phone: '257' },
    { value: 'KH', label: 'Cambodia', phone: '855' },
    { value: 'CM', label: 'Cameroon', phone: '237' },
    { value: 'CA', label: 'Canada', phone: '1', suggested: true },
    { value: 'CV', label: 'Cape Verde', phone: '238' },
    { value: 'KY', label: 'Cayman Islands', phone: '1-345' },
    { value: 'CF', label: 'Central African Republic', phone: '236' },
    { value: 'TD', label: 'Chad', phone: '235' },
    { value: 'CL', label: 'Chile', phone: '56' },
    { value: 'CN', label: 'China', phone: '86' },
    { value: 'CX', label: 'Christmas Island', phone: '61' },
    { value: 'CC', label: 'Cocos (Keeling) Islands', phone: '61' },
    { value: 'CO', label: 'Colombia', phone: '57' },
    { value: 'KM', label: 'Comoros', phone: '269' },
    { value: 'CD', label: 'Congo, Democratic Republic of the', phone: '243' },
    { value: 'CG', label: 'Congo, Republic of the', phone: '242' },
    { value: 'CK', label: 'Cook Islands', phone: '682' },
    { value: 'CR', label: 'Costa Rica', phone: '506' },
    { value: 'CI', label: "Cote d'Ivoire", phone: '225' },
    { value: 'HR', label: 'Croatia', phone: '385' },
    { value: 'CU', label: 'Cuba', phone: '53' },
    { value: 'CW', label: 'Curacao', phone: '599' },
    { value: 'CY', label: 'Cyprus', phone: '357' },
    { value: 'CZ', label: 'Czech Republic', phone: '420' },
    { value: 'DK', label: 'Denmark', phone: '45' },
    { value: 'DJ', label: 'Djibouti', phone: '253' },
    { value: 'DM', label: 'Dominica', phone: '1-767' },
    { value: 'DO', label: 'Dominican Republic', phone: '1-809' },
    { value: 'EC', label: 'Ecuador', phone: '593' },
    { value: 'EG', label: 'Egypt', phone: '20' },
    { value: 'SV', label: 'El Salvador', phone: '503' },
    { value: 'GQ', label: 'Equatorial Guinea', phone: '240' },
    { value: 'ER', label: 'Eritrea', phone: '291' },
    { value: 'EE', label: 'Estonia', phone: '372' },
    { value: 'ET', label: 'Ethiopia', phone: '251' },
    { value: 'FK', label: 'Falkland Islands (Malvinas)', phone: '500' },
    { value: 'FO', label: 'Faroe Islands', phone: '298' },
    { value: 'FJ', label: 'Fiji', phone: '679' },
    { value: 'FI', label: 'Finland', phone: '358' },
    { value: 'FR', label: 'France', phone: '33', suggested: true },
    { value: 'GF', label: 'French Guiana', phone: '594' },
    { value: 'PF', label: 'French Polynesia', phone: '689' },
    { value: 'TF', label: 'French Southern Territories', phone: '262' },
    { value: 'GA', label: 'Gabon', phone: '241' },
    { value: 'GM', label: 'Gambia', phone: '220' },
    { value: 'GE', label: 'Georgia', phone: '995' },
    { value: 'DE', label: 'Germany', phone: '49', suggested: true },
    { value: 'GH', label: 'Ghana', phone: '233' },
    { value: 'GI', label: 'Gibraltar', phone: '350' },
    { value: 'GR', label: 'Greece', phone: '30' },
    { value: 'GL', label: 'Greenland', phone: '299' },
    { value: 'GD', label: 'Grenada', phone: '1-473' },
    { value: 'GP', label: 'Guadeloupe', phone: '590' },
    { value: 'GU', label: 'Guam', phone: '1-671' },
    { value: 'GT', label: 'Guatemala', phone: '502' },
    { value: 'GG', label: 'Guernsey', phone: '44' },
    { value: 'GN', label: 'Guinea', phone: '224' },
    { value: 'GW', label: 'Guinea-Bissau', phone: '245' },
    { value: 'GY', label: 'Guyana', phone: '592' },
    { value: 'HT', label: 'Haiti', phone: '509' },
    { value: 'HM', label: 'Heard Island and McDonald Islands', phone: '672' },
    { value: 'VA', label: 'Holy See (Vatican City State)', phone: '379' },
    { value: 'HN', label: 'Honduras', phone: '504' },
    { value: 'HK', label: 'Hong Kong', phone: '852' },
    { value: 'HU', label: 'Hungary', phone: '36' },
    { value: 'IS', label: 'Iceland', phone: '354' },
    { value: 'IN', label: 'India', phone: '91' },
    { value: 'ID', label: 'Indonesia', phone: '62' },
    { value: 'IR', label: 'Iran, Islamic Republic of', phone: '98' },
    { value: 'IQ', label: 'Iraq', phone: '964' },
    { value: 'IE', label: 'Ireland', phone: '353' },
    { value: 'IM', label: 'Isle of Man', phone: '44' },
    { value: 'IL', label: 'Israel', phone: '972' },
    { value: 'IT', label: 'Italy', phone: '39' },
    { value: 'JM', label: 'Jamaica', phone: '1-876' },
    { value: 'JP', label: 'Japan', phone: '81', suggested: true },
    { value: 'JE', label: 'Jersey', phone: '44' },
    { value: 'JO', label: 'Jordan', phone: '962' },
    { value: 'KZ', label: 'Kazakhstan', phone: '7' },
    { value: 'KE', label: 'Kenya', phone: '254' },
    { value: 'KI', label: 'Kiribati', phone: '686' },
    { value: 'KP', label: "Korea, Democratic People's Republic of", phone: '850' },
    { value: 'KR', label: 'Korea, Republic of', phone: '82' },
    { value: 'XK', label: 'Kosovo', phone: '383' },
    { value: 'KW', label: 'Kuwait', phone: '965' },
    { value: 'KG', label: 'Kyrgyzstan', phone: '996' },
    { value: 'LA', label: "Lao People's Democratic Republic", phone: '856' },
    { value: 'LV', label: 'Latvia', phone: '371' },
    { value: 'LB', label: 'Lebanon', phone: '961' },
    { value: 'LS', label: 'Lesotho', phone: '266' },
    { value: 'LR', label: 'Liberia', phone: '231' },
    { value: 'LY', label: 'Libya', phone: '218' },
    { value: 'LI', label: 'Liechtenstein', phone: '423' },
    { value: 'LT', label: 'Lithuania', phone: '370' },
    { value: 'LU', label: 'Luxembourg', phone: '352' },
    { value: 'MO', label: 'Macao', phone: '853' },
    { value: 'MK', label: 'Macedonia, the Former Yugoslav Republic of', phone: '389' },
    { value: 'MG', label: 'Madagascar', phone: '261' },
    { value: 'MW', label: 'Malawi', phone: '265' },
    { value: 'MY', label: 'Malaysia', phone: '60' },
    { value: 'MV', label: 'Maldives', phone: '960' },
    { value: 'ML', label: 'Mali', phone: '223' },
    { value: 'MT', label: 'Malta', phone: '356' },
    { value: 'MH', label: 'Marshall Islands', phone: '692' },
    { value: 'MQ', label: 'Martinique', phone: '596' },
    { value: 'MR', label: 'Mauritania', phone: '222' },
    { value: 'MU', label: 'Mauritius', phone: '230' },
    { value: 'YT', label: 'Mayotte', phone: '262' },
    { value: 'MX', label: 'Mexico', phone: '52' },
    { value: 'FM', label: 'Micronesia, Federated States of', phone: '691' },
    { value: 'MD', label: 'Moldova, Republic of', phone: '373' },
    { value: 'MC', label: 'Monaco', phone: '377' },
    { value: 'MN', label: 'Mongolia', phone: '976' },
    { value: 'ME', label: 'Montenegro', phone: '382' },
    { value: 'MS', label: 'Montserrat', phone: '1-664' },
    { value: 'MA', label: 'Morocco', phone: '212' },
    { value: 'MZ', label: 'Mozambique', phone: '258' },
    { value: 'MM', label: 'Myanmar', phone: '95' },
    { value: 'NA', label: 'Namibia', phone: '264' },
    { value: 'NR', label: 'Nauru', phone: '674' },
    { value: 'NP', label: 'Nepal', phone: '977' },
    { value: 'NL', label: 'Netherlands', phone: '31' },
    { value: 'NC', label: 'New Caledonia', phone: '687' },
    { value: 'NZ', label: 'New Zealand', phone: '64' },
    { value: 'NI', label: 'Nicaragua', phone: '505' },
    { value: 'NE', label: 'Niger', phone: '227' },
    { value: 'NG', label: 'Nigeria', phone: '234' },
    { value: 'NU', label: 'Niue', phone: '683' },
    { value: 'NF', label: 'Norfolk Island', phone: '672' },
    { value: 'MP', label: 'Northern Mariana Islands', phone: '1-670' },
    { value: 'NO', label: 'Norway', phone: '47' },
    { value: 'OM', label: 'Oman', phone: '968' },
    { value: 'PK', label: 'Pakistan', phone: '92' },
    { value: 'PW', label: 'Palau', phone: '680' },
    { value: 'PS', label: 'Palestine, State of', phone: '970' },
    { value: 'PA', label: 'Panama', phone: '507' },
    { value: 'PG', label: 'Papua New Guinea', phone: '675' },
    { value: 'PY', label: 'Paraguay', phone: '595' },
    { value: 'PE', label: 'Peru', phone: '51' },
    { value: 'PH', label: 'Philippines', phone: '63' },
    { value: 'PN', label: 'Pitcairn', phone: '870' },
    { value: 'PL', label: 'Poland', phone: '48' },
    { value: 'PT', label: 'Portugal', phone: '351' },
    { value: 'PR', label: 'Puerto Rico', phone: '1' },
    { value: 'QA', label: 'Qatar', phone: '974' },
    { value: 'RE', label: 'Reunion', phone: '262' },
    { value: 'RO', label: 'Romania', phone: '40' },
    { value: 'RU', label: 'Russian Federation', phone: '7' },
    { value: 'RW', label: 'Rwanda', phone: '250' },
    { value: 'BL', label: 'Saint Barthelemy', phone: '590' },
    { value: 'SH', label: 'Saint Helena', phone: '290' },
    { value: 'KN', label: 'Saint Kitts and Nevis', phone: '1-869' },
    { value: 'LC', label: 'Saint Lucia', phone: '1-758' },
    { value: 'MF', label: 'Saint Martin (French part)', phone: '590' },
    { value: 'PM', label: 'Saint Pierre and Miquelon', phone: '508' },
    { value: 'VC', label: 'Saint Vincent and the Grenadines', phone: '1-784' },
    { value: 'WS', label: 'Samoa', phone: '685' },
    { value: 'SM', label: 'San Marino', phone: '378' },
    { value: 'ST', label: 'Sao Tome and Principe', phone: '239' },
    { value: 'SA', label: 'Saudi Arabia', phone: '966' },
    { value: 'SN', label: 'Senegal', phone: '221' },
    { value: 'RS', label: 'Serbia', phone: '381' },
    { value: 'SC', label: 'Seychelles', phone: '248' },
    { value: 'SL', label: 'Sierra Leone', phone: '232' },
    { value: 'SG', label: 'Singapore', phone: '65' },
    { value: 'SX', label: 'Sint Maarten (Dutch part)', phone: '1-721' },
    { value: 'SK', label: 'Slovakia', phone: '421' },
    { value: 'SI', label: 'Slovenia', phone: '386' },
    { value: 'SB', label: 'Solomon Islands', phone: '677' },
    { value: 'SO', label: 'Somalia', phone: '252' },
    { value: 'ZA', label: 'South Africa', phone: '27' },
    { value: 'GS', label: 'South Georgia and the South Sandwich Islands', phone: '500' },
    { value: 'SS', label: 'South Sudan', phone: '211' },
    { value: 'ES', label: 'Spain', phone: '34' },
    { value: 'LK', label: 'Sri Lanka', phone: '94' },
    { value: 'SD', label: 'Sudan', phone: '249' },
    { value: 'SR', label: 'Suriname', phone: '597' },
    { value: 'SJ', label: 'Svalbard and Jan Mayen', phone: '47' },
    { value: 'SZ', label: 'Swaziland', phone: '268' },
    { value: 'SE', label: 'Sweden', phone: '46' },
    { value: 'CH', label: 'Switzerland', phone: '41' },
    { value: 'SY', label: 'Syrian Arab Republic', phone: '963' },
    { value: 'TW', label: 'Taiwan', phone: '886' },
    { value: 'TJ', label: 'Tajikistan', phone: '992' },
    { value: 'TH', label: 'Thailand', phone: '66' },
    { value: 'TL', label: 'Timor-Leste', phone: '670' },
    { value: 'TG', label: 'Togo', phone: '228' },
    { value: 'TK', label: 'Tokelau', phone: '690' },
    { value: 'TO', label: 'Tonga', phone: '676' },
    { value: 'TT', label: 'Trinidad and Tobago', phone: '1-868' },
    { value: 'TN', label: 'Tunisia', phone: '216' },
    { value: 'TR', label: 'Turkey', phone: '90' },
    { value: 'TM', label: 'Turkmenistan', phone: '993' },
    { value: 'TC', label: 'Turks and Caicos Islands', phone: '1-649' },
    { value: 'TV', label: 'Tuvalu', phone: '688' },
    { value: 'UG', label: 'Uganda', phone: '256' },
    { value: 'UA', label: 'Ukraine', phone: '380' },
    { value: 'AE', label: 'United Arab Emirates', phone: '971' },
    { value: 'GB', label: 'United Kingdom', phone: '44' },
    { value: 'TZ', label: 'United Republic of Tanzania', phone: '255' },
    { value: 'US', label: 'United States', phone: '1', suggested: true },
    { value: 'UY', label: 'Uruguay', phone: '598' },
    { value: 'VI', label: 'US Virgin Islands', phone: '1-340' },
    { value: 'UZ', label: 'Uzbekistan', phone: '998' },
    { value: 'VU', label: 'Vanuatu', phone: '678' },
    { value: 'VE', label: 'Venezuela', phone: '58' },
    { value: 'VN', label: 'Vietnam', phone: '84' },
    { value: 'WF', label: 'Wallis and Futuna', phone: '681' },
    { value: 'EH', label: 'Western Sahara', phone: '212' },
    { value: 'YE', label: 'Yemen', phone: '967' },
    { value: 'ZM', label: 'Zambia', phone: '260' },
    { value: 'ZW', label: 'Zimbabwe', phone: '263' }
];