# Generated by Django 6.0 on 2026-07-19 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='is_editable',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
