# Generated by Django 6.0 on 2026-08-08 19:00

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0003_abstract_is_editable'),
    ]

    operations = [
        migrations.CreateModel(
            name='PDFGenerationJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('generating', 'Generating'), ('completed', 'Completed'), ('failed', 'Failed')], default='pending', max_length=20)),
                ('file', models.FileField(blank=True, null=True, upload_to='generated/')),
                ('error', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('abstract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pdf_generation_jobs', to='abstracts.abstract')),
            ],
        ),
    ]
