# Generated by Django 6.0 on 2026-08-08 21:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0004_pdfgenerationjob'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdfgenerationjob',
            name='content_hash',
            field=models.CharField(default='nothing', max_length=64),
            preserve_default=False,
        ),
    ]
