# Generated by Django 6.0 on 2026-08-19 20:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0005_pdfgenerationjob_content_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='editable',
            field=models.BooleanField(default=True),
        ),
    ]
