# Generated by Django 6.0 on 2026-08-21 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0006_author_editable'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='is_for_young_watoc',
            field=models.BooleanField(default=False),
        ),
    ]
