# Generated by Django 6.0 on 2026-08-24 02:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0007_abstract_is_for_young_watoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='presentation_type',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('oral', 'Oral Presentation Preferred'), ('poster', 'Poster Presentation Preferred')], db_column='presentation', default='', max_length=10, verbose_name='Tipo de presentación'),
        ),
    ]
