# Generated by Django 6.0 on 2026-08-24 03:45

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abstracts', '0008_alter_abstract_presentation_type'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='affiliation',
            constraint=models.UniqueConstraint(fields=('institution', 'country', 'city', 'user'), name='unique_affiliation_per_user'),
        ),
    ]
