# Generated by Django 6.0 on 2026-02-20 06:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='participant',
            old_name='field_of_stuty',
            new_name='field_of_study',
        ),
    ]
