# Generated by Django 6.0 on 2026-01-07 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='user_type',
            field=models.CharField(choices=[('PARTICIPANT', 'Participant'), ('STUDENT', 'Student')], default='PARTICIPANT', max_length=20),
        ),
    ]
