# Generated by Django 6.0 on 2026-05-28 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='title',
            field=models.TextField(blank=True, db_column='title', verbose_name='Título'),
        ),
    ]
