# Generated by Django 6.0 on 2026-06-26 03:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_abstract_title'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authoraffiliation',
            name='department',
        ),
    ]
