# Generated by Django 6.0 on 2026-02-27 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_user_middle_name_alter_user_pronouns'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='participant',
            name='going_to_dinner',
        ),
        migrations.AddField(
            model_name='dinner',
            name='dietary_needs',
            field=models.CharField(choices=[('veget', 'Vegetarian'), ('vegan', 'Vegan'), ('glut', 'Gluten-free'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('paleo', 'Paleo'), ('fish', 'Pescatarian'), ('other', 'Other restrictions')], default='', max_length=10),
        ),
        migrations.AddField(
            model_name='dinner',
            name='food_allergies',
            field=models.CharField(choices=[('milk', 'Milk'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('crustacean', 'Crustacean'), ('mollusk', 'Mollusk'), ('almond', 'Almond'), ('hazelnut', 'Hazelnut'), ('walnut', 'Walnut'), ('peanuts', 'Peanuts'), ('wheat', 'Wheat (Gluten)'), ('soybeans', 'Soybeans'), ('other', 'Other')], db_default='', default=False),
        ),
        migrations.AddField(
            model_name='dinner',
            name='has_dietary_restriction',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinner',
            name='has_food_allergy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='dinner',
            name='other_allergies',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='dinner',
            name='other_dietary_needs',
            field=models.CharField(blank=True, max_length=75),
        ),
        migrations.AddField(
            model_name='dinner',
            name='will_assist_dinner',
            field=models.BooleanField(default=False),
        ),
    ]
