# Generated by Django 6.0 on 2026-01-28 06:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_passwordresetcode'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='secondary_email',
        ),
    ]
