# Generated by Django 6.0 on 2026-02-27 07:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_remove_participant_going_to_dinner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='dietary_needs',
            field=models.CharField(choices=[('', 'Not set'), ('veget', 'Vegetarian'), ('vegan', 'Vegan'), ('glut', 'Gluten-free'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('paleo', 'Paleo'), ('fish', 'Pescatarian'), ('other', 'Other restrictions')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='food_allergies',
            field=models.CharField(choices=[('', 'Not set'), ('milk', 'Milk'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('crustacean', 'Crustacean'), ('mollusk', 'Mollusk'), ('almond', 'Almond'), ('hazelnut', 'Hazelnut'), ('walnut', 'Walnut'), ('peanuts', 'Peanuts'), ('wheat', 'Wheat (Gluten)'), ('soybeans', 'Soybeans'), ('other', 'Other')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='participant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='users.participant'),
        ),
    ]
