# Generated by Django 6.0 on 2026-02-27 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_abstractdeclarations_authoraffiliation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authoraffiliation',
            old_name='job_title',
            new_name='department',
        ),
        migrations.AlterField(
            model_name='dinner',
            name='dietary_needs',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('veget', 'Vegetarian'), ('vegan', 'Vegan'), ('glut', 'Gluten-free'), ('halal', 'Halal'), ('kosher', 'Kosher'), ('paleo', 'Paleo'), ('fish', 'Pescatarian'), ('other', 'Other restrictions')], default='', max_length=10),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='food_allergies',
            field=models.CharField(blank=True, choices=[('', 'Not set'), ('milk', 'Milk'), ('eggs', 'Eggs'), ('fish', 'Fish'), ('crustacean', 'Crustacean'), ('mollusk', 'Mollusk'), ('almond', 'Almond'), ('hazelnut', 'Hazelnut'), ('walnut', 'Walnut'), ('peanuts', 'Peanuts'), ('wheat', 'Wheat (Gluten)'), ('soybeans', 'Soybeans'), ('other', 'Other')], default='', max_length=10),
        ),
    ]
