# Generated by Django 6.0 on 2026-02-27 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_rename_job_title_authoraffiliation_department_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='authoraffiliation',
            old_name='affiliation',
            new_name='institute',
        ),
    ]
