# Generated by Django 6.0 on 2026-02-28 03:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_rename_affiliation_authoraffiliation_institute'),
    ]

    operations = [
        migrations.AddField(
            model_name='authoraffiliation',
            name='abstract',
            field=models.ForeignKey(db_column='abstract', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='affiliations', to='users.abstract'),
        ),
    ]
