# Generated by Django 6.0 on 2026-03-02 02:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_authoraffiliation_abstract'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='presentation_type',
            field=models.CharField(choices=[('', 'Not set'), ('oral', 'Oral Presentation Preferred'), ('poster', 'Poster Presentation Preferred')], db_column='presentation', default='', verbose_name='Tipo de presentación'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='references',
            field=models.TextField(blank=True, db_column='references', verbose_name='Referencias'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='text',
            field=models.TextField(blank=True, db_column='text', verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='title',
            field=models.CharField(blank=True, db_column='title', max_length=128, verbose_name='Título'),
        ),
        migrations.AlterField(
            model_name='author',
            name='email',
            field=models.EmailField(blank=True, max_length=254),
        ),
    ]
