# Generated by Django 6.0 on 2026-03-10 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_alter_abstract_presentation_type_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together={('abstract', 'order')},
        ),
        migrations.AlterField(
            model_name='participant',
            name='invitation_letter',
            field=models.FileField(blank=True, default=None, upload_to='users/invitation_letter/'),
        ),
        migrations.RemoveField(
            model_name='author',
            name='is_corresponding',
        ),
    ]
