# Generated by Django 6.0 on 2026-03-10 22:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_alter_author_unique_together_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='author',
            unique_together=set(),
        ),
    ]
