# Generated by Django 6.0 on 2026-03-14 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0011_alter_author_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abstract',
            name='presentation_type',
            field=models.CharField(choices=[('', 'Not set'), ('oral', 'Oral Presentation Preferred'), ('poster', 'Poster Presentation Preferred')], db_column='presentation', default='', max_length=10, verbose_name='Tipo de presentación'),
        ),
        migrations.AlterField(
            model_name='abstract',
            name='status',
            field=models.CharField(choices=[('deleted', 'Eliminado'), ('draft', 'Borrador'), ('submitted', 'Enviado / En revisión'), ('accepted', 'Aceptado'), ('rejected', 'Rechazado')], db_column='status', default='draft', max_length=16, verbose_name='Estado del abstract'),
        ),
        migrations.AlterField(
            model_name='author',
            name='first_name',
            field=models.CharField(blank=True, max_length=128),
        ),
        migrations.AlterField(
            model_name='author',
            name='last_name',
            field=models.CharField(blank=True, max_length=128),
        ),
    ]
