# Generated by Django 6.0 on 2026-05-13 08:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0014_alter_tour_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(error_messages={'invalid': 'That email format looks wrong.', 'unique': 'This email is already registered.'}, max_length=254, unique=True),
        ),
    ]
