# Generated by Django 6.0 on 2026-05-14 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0016_alter_user_options_alter_user_table'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='participant',
            table='participant',
        ),
    ]
