# Generated by Django 6.0 on 2026-05-15 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0017_alter_participant_table'),
    ]

    operations = [
        migrations.AddField(
            model_name='abstract',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
