# Generated by Django 6.0 on 2026-05-16 03:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_abstract_email_verified'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='abstract',
            name='email_verified',
        ),
        migrations.AddField(
            model_name='user',
            name='email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
