export const DEBUG = import.meta.env.VITE_DEBUG === 'true'

export const feePlans = [
    {
        value: 0,
        id: "participant-early",
        title: "Participant",
        description: "Early Bird",
        label: '1 Oct 2024 — 28 Feb 2025',
        price: 15_000,
        currency: 'MXN',
        student_fee: false,
    },
    {
        value: 1,
        id: "participant-regular",
        title: "Participant",
        description: "Regular attendee",
        label: '1 Oct 2024 — 28 Feb 2025',
        price: 17_000,
        currency: 'MXN',
        student_fee: false,
    },
    {
        value: 2,
        id: "participant-late",
        title: "Participant",
        description: "Late",
        label: '1 Oct 2024 — 28 Feb 2025',
        price: 18_000,
        currency: 'MXN',
        student_fee: false,
    },
    {
        value: 3,
        id: "student-early",
        title: "Student",
        description: "Early Bird",
        label: '1 Oct 2024 — 28 Feb 2025',
        price: 7_500,
        currency: 'MXN',
        student_fee: true,
    },
    {
        value: 4,
        id: "student-regular",
        title: "Student",
        description: "Regular student",
        label: '1 Oct 2024 — 28 Feb 2025',
        price: 7_500,
        currency: 'MXN',
        student_fee: true,
    },
    {
        value: 5,
        id: "student-late",
        title: "Student",
        description: "Late",
        label: '1 Oct 2024 — 28 Feb 2025',
        price: 7_500,
        currency: 'MXN',
        student_fee: true,
    },
] as const
